### ISSUE TITLE
Virus warning from BitDefender / Large icon.png

### ISSUE THREAD

**Issue by MarkusBordihn** [YUNG-GANG/Travelers-Titles#17]
Hi Nick,
first of all thanks for all of your hard work, I really like your mods. ;)

It's seems that the version `TravelersTitles-1.18.2-Forge-2.1.1.jar` and `TravelersTitles-1.18.2-Forge-2.1.0.jar` are report as infected with `Java.Trojan.GenericGB.29351` in the file `TitleRenderer.class` by BitDefender Total Security.

![image](https://user-images.githubusercontent.com/12183293/168650590-84b285b8-93a1-4c00-adb1-625b1da845e0.png)

Looks like a false positive for me, but would be great if this could be fixed.

Furthermore it would be great if you can minimize the file https://github.com/YUNG-GANG/Travelers-Titles/blob/multiloader/1.18/Common/src/main/resources/icon.png with https://tinypng.com/ or so.

Any PNG optimization should be able to lower the icon file size by 50% (about 100kb) which is about 30% of the current mod file size.

**Comment by yungnickyoung** [comment]
Hey! Yeah, it's a false positive. Unfortunately there's not much I can do except rearrange some things in the TitleRenderer class and hope that it no longer gets detected. In the meantime, please report the file as a false positive - hopefully I can get them to manually whitelist it.

As for PNG optimization - thanks for the pointer! I'll try and do that with all my mods in the future.

**Comment by MarkusBordihn** [comment]
I reported the file to Bit Defender Support and it seems the false positive is fixed, so I will close this issue. ;)
