### ISSUE TITLE
Feature Request: subtitle and debug commands

### ISSUE THREAD

**Issue by bucketBrian** [YUNG-GANG/Travelers-Titles#2]
As mentioned above, add a subtitle with smaller font above or below the main title.
This feature is mostly for modpacks, so it should be blank in default.
also this mod should add some debug commands for developers. here are some commands I think it should have:
- list the available biomes with their titles
- show a specified titles (even when not in the correct biome)
- a test command to quickly check the effects of the title

**Comment by yungnickyoung** [comment]
Some great ideas here. Although I'm not sure how practical it is to list all biomes and their titles. Can you elaborate on what you mean by checking the effects of the title?

**Comment by yungnickyoung** [comment]
Added /biometitle and /dimensiontitle in v1.3.

**Comment by bucketBrian** [comment]
firstly thanks for using some of my ideas!
![2021-07-20_12 14 46](https://user-images.githubusercontent.com/48875131/126476708-09c9b3b1-2771-48ff-8e6d-b1b9ea0ed287.png)
secondly, the reason of why I will ask for biomes list is for this.
Is probably a subbiome from Autumnity ,which use to spawn some maple tree in dark forest.
I know I can use biome group, but I don't know where to get it's "codename", I'm not very good at this area.

**Comment by bucketBrian** [comment]
ohh, surry for being ignorance! I didn't notice's that I can actually find it in any command relate to biomes!

**Comment by bucketBrian** [comment]
And by the way, did you intend to add subtitles?
