### ISSUE TITLE
Resourcepack not working

### ISSUE THREAD

**Issue by Gamerbolts** [YUNG-GANG/Travelers-Titles#24]
Hello. I tried to create a resourcepack with titles for Space Dimensions, Dimensional Doors etc and when I enter the dimension it still gives me the ??? I am not sure if I did something wrong

the resourcepack is
assets/travelerstitles/lang/en_us.json and pack.mcmeta is in the zip folder.

Here is the json:
{
	"travelerstitles.agape.europa_ocean": "Europa Ocean",
	"travelerstitles.agape.europa_surface": "Europa",
	"travelerstitles.agape.ganymede": "Ganymede",
	"travelerstitles.agape.io": "Io",
	"travelerstitles.agape.mercury": "Mercury",
	"travelerstitles.agape.moon_surface": "The Moon",
	"travelerstitles.agape.red_planet": "Mars",
	"travelerstitles.agape.starship_1": "Starship",
	"travelerstitles.agape.titan": "Titan",
	"travelerstitles.agape.venus_clouds": "Venus",
	"travelerstitles.agape.venus_surface": "Venus",
	
	"travelerstitles.mining_dims.caving_dim": "Caving Dimension",
	"travelerstitles.mining_dims.climbing_dim": "Climbing Dimension",
	"travelerstitles.mining_dims.hunting_dim": "Hunting Dimension",
	"travelerstitles.mining_dims.mining_dim": "Mining Dimension",
	"travelerstitles.mining_dims.nethering_dim": "Nethering Dimension",
	
	"travelerstitles.dimdoors.limbo": "Limbo",
	"travelerstitles.dimdoors.personal_pockets": "Personal Pocket",
	"travelerstitles.dimdoors.public_pockets": "Public Pocket",
	
	"travelerstitles.pswgextra.hoth": "Hoth",
	"travelerstitles.pswgextra.mandalore": "Mandalore",
	
	"travelerstitles.spectrum.deeper_down_dimension": "Deeper Down",
	
	"travelerstitles.the_aether.the_aether": "The Aether",
	
	"travelerstitles.voidz.void": "The Void"
}

Not sure why it is not working. Any help appreciated. Thank you!

**Comment by yungnickyoung** [comment]
Sorry I'm probably way too late to help with this lol. In the future if you need help getting my mods set up please ask in the [Discord](https://discord.gg/yung)!
