### ISSUE TITLE
NPE crash when joining server

### ISSUE THREAD

**Issue by SHXRKIEgg** [YUNG-GANG/Travelers-Titles#3]
Getting this crash when trying to join Multiplayer server, works fine on Singleplayer
https://pastebin.com/w0CrRdbn

**Comment by yungnickyoung** [comment]
At first glance, looks like it may be that I need to access the biome's registry name through methods specific to the client world rather than the way it's normally done during worldgen. I'll fix this later today

**Comment by yungnickyoung** [comment]
Crash is hotfixed. Biome titles are currently broken on multiplayer servers - I'll revisit it later today when I have some more time.

**Comment by yungnickyoung** [comment]
Should be fixed in v1.2.2. Let me know if it works for you

**Comment by yungnickyoung** [comment]
Tested my self and seems to work. Closing for now
