### ISSUE TITLE
[Suggestion] Custom sounds for each biome and ability to rename biomes

### ISSUE THREAD

**Issue by CTN-0452-9** [YUNG-GANG/Travelers-Titles#38]
1. I think it'd be cool to have the ability to configure a unique sound for each individual biomes instead of one sound for all biomes or all dimensions.

2. It would also be dope to rename biomes, like have an item in game that can change the the title of one specific biome. For example maybe a beach is of significance to the world and players can rename it to reflect that instead of just seeing "Beach".

Great mod though :) 👍

**Comment by CaptFarosh** [comment]
I second this notion

**Comment by MrGreenTea** [comment]
The second part can be achieved with the areas mod: https://www.curseforge.com/minecraft/mc-mods/areas

**Comment by yungnickyoung** [comment]
At the moment we're just sticking with one sound for all biomes, but I'm open to looking into improving that in the future.

For the second part, another alternative is to use the Waystones mod. If you're on Forge 1.18+, Traveler's Titles will display the title of nearby waystones, so you could put a waystone on the beach
