### ISSUE TITLE
Suggestion: New way of getting the dimension title that could work for anything

### ISSUE THREAD

**Issue by TheOtherworldly** [YUNG-GANG/Travelers-Titles#39]
There is a way, I'm not sure if it is that good, but it is something I use for my own mod, but I did it for biomes instead. You are able to reach from the debug menu (f3 screen). On the menu is a place that displays the current dimension. If you use basic string methods you can pick that part out and change it from the id format, by replacing underscores with spaces and I use other methods to capitalize the first letters (I dont remember how but I did it) and then you can get the dimension for any dimension for any mod, without needing to add them.

**Comment by yungnickyoung** [comment]
True, I could parse the dimension's ID like that. Although just so you know you don't need to grab that from the F3 menu lol. But thanks for the tip!
