### ISSUE TITLE
[Request] Support for Blue Skies in the dimension title list

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [YUNG-GANG/Travelers-Titles#4]
Hi,

First of all I want to say that this is a great little mod and I've really enjoyed using it thus far! You always do fantastic work on your mods and this is no exception!

Secondly, when I've been using this mod in my modpack I've noticed that it doesn't have support for the Blue Skies mod and the dimensions added by it. Whenever I enter one of these two dimensions it just displays three question marks where the name of the dimension should be (although biome names work just fine), like so:
![2021-07-19_23 42 44](https://user-images.githubusercontent.com/64381954/126237624-42f782c3-898e-44c1-95da-b52176aed01b.png)

It would be great if support for this dimension mod could be added in order for this mod to be consistent with the other dimensions that I have in my modpack. Here's a link to the mod's page: https://www.curseforge.com/minecraft/mc-mods/blue-skies

Thanks for all the fantastic mods you've made!

**Comment by yungnickyoung** [comment]
Added in v1.3!
