### ISSUE TITLE
Support for 1.20   We need you! really! update pls!

### ISSUE THREAD

**Issue by HMwancheng** [YUNG-GANG/Travelers-Titles#40]

**Comment by HMwancheng** [comment]
i'm so sorry...but   didn't update now?

**Comment by suerion** [comment]
it is updated, but you need to wait to public release, YUNG had an VIP release, but there you need an patreon sub ;)

**Comment by HMwancheng** [comment]
> 

aha, get it , thank you! i'll wating it comming to public
actually，i like this title when me walking in my world, it's interesting
