### ISSUE TITLE
[Question]Aleady update to 1.20.1 but no upload?

### ISSUE THREAD

**Issue by HMwancheng** [YUNG-GANG/Travelers-Titles#41]
only for you marking complete in old issue but i don't find it on modrinth & curseforge

**Comment by HMwancheng** [comment]
i see in your old issue ,  maybe you'll update for you customer first？

**Comment by yungnickyoung** [comment]
The 1.20+ releases are currently Patreon only. There will be public releases in the future at some point.

**Comment by HMwancheng** [comment]
Patreon? Patron    
ok~ get it~
