### ISSUE TITLE
Biome Title config - Text Size resetting to Default value

### ISSUE THREAD

**Issue by Snugs** [YUNG-GANG/Travelers-Titles#52]
As the title of this issue suggests, I've been trying to change the text size of the Biome Titles via the config file, and while every other value I've changed so far has persisted, the Biome Titles Text Size has been resetting to the default value every time I load Minecraft. No other values I've changed so far have had this issue. Currently running the Forge version of the mod for 1.20.1, loaded via the NeoForge loader for 1.20.1 (compatible with Forge). If you need any more info I'll be happy to assist! :D

**Comment by yungnickyoung** [comment]
Sorry I'm so late on this.

Try closing the game first before making the modification to the config file. Sometimes Forge can be buggy when it comes to editing configs while the game is open.

Other than that, double check that you're providing a valid value. It reverting could mean that the value you provided was invalid.

**Comment by Snugs** [comment]
No worries mate, I understand life gets busy ^_^

Thank you for the insightful response! This is my first modpack for Forge so I had no idea Forge had issues with config values being changed while the instance was still open. Resetting the text size while the game was closed has indeed fixed the issue. I'll make sure to keep this new knowledge in mind for all my future config changes :')
