### ISSUE TITLE
The titles are duplicated

### ISSUE THREAD

**Issue by Kevlanikov** [YUNG-GANG/Travelers-Titles#55]
![2024-03-03_22 30 50](https://github.com/YUNG-GANG/Travelers-Titles/assets/161832309/d29ee03c-02f6-4326-9adf-61cfa04a8cc8)

**Comment by ImWhiff** [comment]
pretty sure that yellow title is from Vanilla Refresh. Disable one or the other

**Comment by Kevlanikov** [comment]
> pretty sure that yellow title is from Vanilla Refresh. Disable one or the other

Yeah it is. Thank you!
