### ISSUE TITLE
Are titles shown only once per biom?

### ISSUE THREAD

**Issue by danielr1996** [YUNG-GANG/Travelers-Titles#62]
It seems that the titles are only shown the first time you enter a biom, is this intended? I'd really like to see the titles everytime I change biom, because with many biom mods it get quite hard to identify the biom you're in.

**Comment by AndreiToroplean** [comment]
Hello, I had the same issue. But it's easy to fix by tweaking a few settings. There's mainly two that you should look into (I don't have Minecraft opened at the moment so I might not have the exact names):
1. The "Number of recent biomes". By default it's 5, drop it to 0 if you want the biome names to reappear when you go back and forth between two biomes.
2. The "Cooldown time". Again, drop it to 0 if you want the biome name to reappear if you come back to a biome *immediately* after leaving it.

**Comment by danielr1996** [comment]
Thank you very much, that fixed it!
